apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: quiz
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
        domains:
          - "challs.csc.tf"
  healthcheck:
    enabled: false # TIP: disable the healthcheck during development
